version: 2
before:
  hooks:
    - go mod tidy
    - ./scripts/completions.sh
builds:
  - id: cli
    main: ./cmd/cli
    binary: ai
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -w -s
        -X github.com/joern1811/ai/internal/version.Version={{ .Version }}
        -X github.com/joern1811/ai/internal/version.GitCommit={{ .FullCommit }}
        -X github.com/joern1811/ai/internal/version.BuildDate={{ .Date }}
  - id: rest
    main: ./cmd/rest
    binary: ai-server
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
archives:
  - id: cli
    builds:
      - cli
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    files:
      - completions/*
  - id: rest
    builds:
      - rest
    name_template: >-
      {{ .Binary }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
checksum:
  name_template: 'checksums.txt'
snapshot:
  version_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
brews:
  - name: ai
    ids:
      - cli
    repository:
      owner: joern1811
      name: homebrew-tap
    commit_author:
      name: Jörn Dombrowski
      email: joern.dombrowski@gmail.com
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    directory: Formula
    homepage: "https://github.com/joern1811/ai"
    license: "Apache-2.0"
    install: |-
      bin.install "ai"
      bash_completion.install "completions/ai.bash" => "ai"
      zsh_completion.install "completions/ai.zsh" => "_ai"
      fish_completion.install "completions/ai.fish"

dockers:
  - id: rest_amd64
    ids:
      - rest
    goarch: amd64
    image_templates:
      - "ghcr.io/joern1811/ai:{{ .Version }}-amd64"
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - --platform=linux/amd64
      - --pull
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.name={{.ProjectName}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.version={{.Version}}
      - --label=org.opencontainers.image.source={{.GitURL}}
  - id: rest_arm64
    ids:
      - rest
    goarch: arm64
    image_templates:
      - "ghcr.io/joern1811/ai:{{ .Version }}-arm64v8"
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - --platform=linux/arm64/v8
      - --pull
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.name={{.ProjectName}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.version={{.Version}}
      - --label=org.opencontainers.image.source={{.GitURL}}

docker_manifests:
  - name_template: "ghcr.io/joern1811/ai:{{ .Version }}"
    image_templates:
      - "ghcr.io/joern1811/ai:{{ .Version }}-amd64"
      - "ghcr.io/joern1811/ai:{{ .Version }}-arm64v8"
  - name_template: "ghcr.io/joern1811/ai:latest"
    image_templates:
      - "ghcr.io/joern1811/ai:{{ .Version }}-amd64"
      - "ghcr.io/joern1811/ai:{{ .Version }}-arm64v8"
