# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    #- go generate ./...
    - ./scripts/completions.sh
builds:
  - main: ./cmd/
    binary: ai
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ldflags:
      - -w -s
        -X github.com/joern1811/ai/internal/version.Version={{ .Version }}
        -X github.com/joern1811/ai/internal/version.GitCommit={{ .FullCommit }}
        -X github.com/joern1811/ai/internal/version.BuildDate={{ .Date }}
archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    files:
     - completions/*
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
# .goreleaser.yaml
brews:
  - name: ai
    # GitHub/GitLab repository to push the formula to
    tap:
      owner: joern1811
      name: homebrew-tap

    # Allows you to set a custom download strategy. Note that you'll need
    # to implement the strategy and add it to your tap repository.
    # Example: https://docs.brew.sh/Formula-Cookbook#specifying-the-download-strategy-explicitly
    # Default is empty.
    download_strategy: CurlDownloadStrategy

    # Allows you to add a custom require_relative at the top of the formula template
    #custom_require: "lib/custom_download_strategy"

    # Git author used to commit to the repository.
    # Defaults are shown.
    commit_author:
      name: Jörn Dombrowski
      email: joern.dombrowski@gmail.com

    # The project name and current git tag are used in the format string.
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"

    # Folder inside the repository to put the formula.
    # Default is the root folder.
    folder: Formula

    # Your app's homepage.
    # Default is empty.
    homepage: "https://github.com/joern1811/ai"

    # Template of your app's description.
    # Default is empty.
    description: ""

    # SPDX identifier of your app's license.
    # Default is empty.
    license: "Apache-2.0"

    install: |-
      bin.install "ai"
      bash_completion.install "completions/ai.bash" => "ai"
      zsh_completion.install "completions/ai.zsh" => "_ai"
      fish_completion.install "completions/ai.fish"


# modelines, feel free to remove those if you don't want/use them:
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
